version: "3"
services:
  strapi:
    build:
      context: ./docker/strapi/
      args:
        NODE_VERSION: 16.8.0
        BASE_VERSION: latest
        STRAPI_VERSION: 4.0.3
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      AWS_ACCESS_KEY_ID:
      AWS_ACCESS_SECRET:
      AWS_REGION:
      AWS_BUCKET:
      CDN_BASE_URL:
    volumes:
      - ./app:/srv/app
    ports:
      - 1337:1337
    depends_on:
      - postgres

  web:
    build:
      context: ./docker/web/
    volumes:
      - ./web:/srv/web
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
    depends_on:
      - strapi
    hostname: web
    networks:
      - strapi
    # tty: true
    # stdin_open: true
    # privileged: true
    # entrypoint: /sbin/init
    platform: linux/x86_64    # ← この設定を追加する

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432


networks:
  strapi:
    name: Strapi
    driver: bridge
